### PR TITLE
Create job page

### PR DESCRIPTION
**Pull request by jdd1260**
This sets up a page that allows the user to create a job with a name, data url, map function, and reduce function. Clicking submit uses the create job lambda to create and store a job. Once it succeeds, it redirects the user to the results page.

I also went ahead and removed some more files that we didn't need.

### CODE REVIEW

**Review by arift — APPROVED** [review]

**Review by colanconnon — APPROVED** [review]
LGTM. We need to update the backend to match this.

**Comment by jdd1260** [comment]
@colanconnon this works with the current back end. Were you not able to try it out?

**Comment by colanconnon** [comment]
@jdd1260 it works buts it's not saving the fields besides the name

**Comment by jdd1260** [comment]
@colanconnon oh good catch. Yeah I didn't realize that we had to define all the fields for DynamoDB. I'm mostly familiar with MongoDB.

**Pull request merged**
